name: Hello workflow

on: 
  push:
    branches: [main] 

jobs:

  greet:
    steps:
      - name: say hello to users
        run: echo"hello Doston"

      - name: say hello to username
        run: echo"hello $USER"
